package VIEW;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Cleit
 */
public class FrmMainVIEW extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainVIEW
     */
    public FrmMainVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUser = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuRegister = new javax.swing.JMenu();
        menuRegisterUser = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        menuEditUser = new javax.swing.JMenuItem();
        menuDelete = new javax.swing.JMenu();
        menuDeleteUser = new javax.swing.JMenuItem();
        menuOption = new javax.swing.JMenu();
        menuOptionGoOut = new javax.swing.JMenuItem();
        menuListUsers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(880, 680));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblUser.setText("Usuário");

        lblDate.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDate.setText("Data");

        desktop.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        menuRegister.setText("Cadastrar");

        menuRegisterUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menuRegisterUser.setText("Usuário");
        menuRegisterUser.setEnabled(false);
        menuRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegisterUserActionPerformed(evt);
            }
        });
        menuRegister.add(menuRegisterUser);

        menuBar.add(menuRegister);

        menuEdit.setText("Editar");

        menuEditUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        menuEditUser.setText("Usuario");
        menuEdit.add(menuEditUser);

        menuBar.add(menuEdit);

        menuDelete.setText("Deletar");

        menuDeleteUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        menuDeleteUser.setText("Usuário");
        menuDeleteUser.setEnabled(false);
        menuDelete.add(menuDeleteUser);

        menuBar.add(menuDelete);

        menuOption.setText("Opções");

        menuOptionGoOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        menuOptionGoOut.setText("Sair");
        menuOptionGoOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOptionGoOutActionPerformed(evt);
            }
        });
        menuOption.add(menuOptionGoOut);

        menuListUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        menuListUsers.setText("Listar usuários");
        menuListUsers.setEnabled(false);
        menuListUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListUsersActionPerformed(evt);
            }
        });
        menuOption.add(menuListUsers);

        menuBar.add(menuOption);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lblUser)
                        .addGap(46, 46, 46)
                        .addComponent(lblDate))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // substitui a label lblDate pela data atual do sistema ao inicia o form
        Date date = new Date();
        DateFormat dateFormat = DateFormat.getDateInstance(DateFormat.SHORT);
        lblDate.setText(dateFormat.format(date));

    }//GEN-LAST:event_formWindowActivated

    private void menuOptionGoOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOptionGoOutActionPerformed
        //exibe uma caixa de diálogo JOptionPane
        int goOut = JOptionPane.showConfirmDialog(null, "Tem serteza que deseja sair? ", "Atenção", JOptionPane.YES_OPTION);

        if (goOut == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuOptionGoOutActionPerformed

    private void menuRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegisterUserActionPerformed
        // chama tela de cadastro de usuário dentro do desktop
        FrmUserCreateVIEW userView = new FrmUserCreateVIEW();
        userView.setVisible(true);
        desktop.add(userView);
    }//GEN-LAST:event_menuRegisterUserActionPerformed

    private void menuListUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListUsersActionPerformed
        FrmListUsersVIEW listUserView = new FrmListUsersVIEW();
        listUserView.setVisible(true);
    }//GEN-LAST:event_menuListUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMainVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMainVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel lblDate;
    public static javax.swing.JLabel lblUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuDelete;
    public static javax.swing.JMenuItem menuDeleteUser;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenuItem menuEditUser;
    public static javax.swing.JMenuItem menuListUsers;
    private javax.swing.JMenu menuOption;
    private javax.swing.JMenuItem menuOptionGoOut;
    private javax.swing.JMenu menuRegister;
    public static javax.swing.JMenuItem menuRegisterUser;
    // End of variables declaration//GEN-END:variables
}
